version: '3.1'
services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./temp/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network

  redmine:
    image: redmine:5.1.2-alpine3.18
    container_name: redmine-local
    depends_on: 
      - postgres
    restart: always
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: 12345
    ports:
      - 8180:3000
    networks:
      - local-network

  localstack:
    image: localstack/localstack
    container_name: localstack_local
    ports: 
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - ./temp/localstack:/var/lib/localstack
    networks:
      - local-network

networks:
  local-network:
    name: local-network

